
export const ozellikler = {
    yetenekler: ['radyasyon-emer', 'hava-temizler'],
    tarz: ['col', 'tropik', 'minimal'],
    hissiyat:['ciddi', 'rahat'],
    renkli:['cicekli'],
    bakimIstegi: ['cok-bakim', 'az'],
    isikIstegi: ['aydinlik', 'golge', 'yari-aydinlik'],
    buyume: ['hizli', 'orta', 'yavas'],
    yaprakOzelligi: ['diken', 'buyuk', 'kucuk'],
    form: ['sarkici', 'dikey', 'daginik'],
    sicaklik: ['az', 'orta', 'yuksek'],
    nem: ['yuksek', 'ev']

}

export const bitkiler = [
    {
    bitkiAdi:'Monstera deliciosa - DEVE TABANI',
    yetenekler:['radyasyon-emer','hava-temizler'],
    tarz: ['tropik'],
    hissiyat:['rahat'],
    renkli:[],
    bakimIstegi:['az'],
    isikIstegi:['golge'],
    buyume:['orta'],
    yaprakOzelligi:['buyuk'],
    form:['daginik'],
    sicaklik:['orta'],
    nem: ['yuksek']
    },
    {
        bitkiAdi:'Ficus elastica - KAUÇUK',
        yetenekler:['radyasyon-emer','hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['cok-bakim'],
        isikIstegi:['aydinlik', 'yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['dikey'],
        sicaklik:['orta'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Codiaeum variegatum - KROTON',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['cok-bakim'],
        isikIstegi:['yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['dikey'],
        sicaklik:['az'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Calathea Ornata- DUA ÇİÇEĞİ',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['cok-bakim'],
        isikIstegi:['yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['daginik'],
        sicaklik:['az'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Pilea Peperomioides-ÇİN PARA- PİLEA',
        yetenekler:[],
        tarz: ['tropik','minimal'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['yari-aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['ev']
    },
    {
        bitkiAdi:'Zamioculcas Zamiifolia - ZAMİA',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['yari-aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['kucuk'],
        form:['dikey'],
        sicaklik:['dusuk'],
        nem: ['ev']
    },
    {
        bitkiAdi:'Stralitzia Nicolai -STARLİÇE',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat', 'ciddi'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['buyuk'],
        form:['dikey'],
        sicaklik:['yuksek'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Dypsis Lutescens -AREKA PALMİYESİ',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['ev']
    },
    {
        bitkiAdi:'Asparagus plumosus - KUŞKONMAZ',
        yetenekler:[],
        tarz: ['minimal','tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['yuksek'],
        isikIstegi:['aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['az'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Ficus benjamina - BENJAMİN',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['yuksek'],
        isikIstegi:['golge','yari-aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Dieffenbachia Seguine - DİFENBAHYA',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['golge','yari-aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['buyuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['yuksek']
    },
    {
        bitkiAdi:'Opuntia M. Albata - KAKTÜS TAVŞAN K.',
        yetenekler:['radyasyon-emer'],
        tarz: ['col','minimal'],
        hissiyat:['ciddi','rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik','yari-aydinlik','golge'],
        buyume:['yavas'],
        yaprakOzelligi:['diken'],
        form:['dikey'],
        sicaklik:['yuksek'],
        nem: ['ev']
    },
]

