import images from './images/images';

export const ozellikler = {
    yetenekler: ['radyasyon-emer', 'hava-temizler'],
    tarz: ['col', 'tropik', 'minimal'],
    hissiyat:['ciddi', 'rahat'],
    renkli:['cicekli'],
    bakimIstegi: ['cok-bakim', 'az'],
    isikIstegi: ['aydinlik', 'golge', 'yari-aydinlik'],
    buyume: ['hizli', 'orta', 'yavas'],
    yaprakOzelligi: ['diken', 'buyuk', 'kucuk'],
    form: ['sarkici', 'dikey', 'daginik'],
    sicaklik: ['az', 'orta', 'yuksek'],
    nem: ['yuksek', 'ev']

}
export const keys = ['form', 'isikIstegi', 'sicaklik', 'bakimIstegi', 'tarz'];
export const sorular = [
    {
        id: 1, 
        soru: 'Bitkiniz için mekanınızı seçin !' , 
        siklar:['Ofis-İş Ortamı', 'Ev Ortamı', 'Cafe - Restaurant'],
        cevap:['dikey', 'daginik,dikey,sarkici', 'dikey,daginik,sarkici']
    },
    {
        id: 2, 
        soru: 'Bitkinizi kullanacağınız ortam ışık alımı yönünden nasıldır?' , 
        siklar:['Aydınlık, sürekli ışık alan', 'Yarı aydınlık, belirli saatlerde ışık alan', 'Gölge, ışık almayan'],
        cevap:['aydinlik', 'yari-aydinlik',  'golge']
    },
    {
        id: 3, 
        soru: 'Bitkinizi kullanacağınız ortam sıcaklık yönünden nasıldı ?' , 
        siklar:['Yüksek sıcaklık', 'Orta sıcaklık', 'Düşük sıcaklık'],
        cevap:['yuksek', 'orta',  'az']
    },
    {
        id: 4, 
        soru: 'Bitkinizle tahmini ne sıklıkla ilgilenirsiniz?' , 
        siklar:['Her gün mutlaka kontrol ederim', 'Haftada 1,2 kontrol ederim', 'Aklıma ne zaman gelirse', 'Bakımı ile ilgilenecek hiç zamanım olmaz'],
        cevap:['cok-bakim,az', 'cok-bakim,az', 'az', 'az']
    },
    {
        id: 5, 
        soru: 'Bitkiniz mekanınıza nasıl bir hava versin istersiniz ?' , 
        siklar:['Çöl havası', 'Tropik hava','Bana bitki olsun yeter'],
        cevap:['col', 'tropik', 'col,tropik,minimal']
    },
]


export const bitkiler = [
    {
    bitkiAdi:'Monstera deliciosa - DEVE TABANI',
    yetenekler:['radyasyon-emer','hava-temizler'],
    tarz: ['tropik'],
    hissiyat:['rahat'],
    renkli:[],
    bakimIstegi:['az'],
    isikIstegi:['golge'],
    buyume:['orta'],
    yaprakOzelligi:['buyuk'],
    form:['daginik'],
    sicaklik:['orta'],
    nem: ['yuksek'],
    imageUrl: images[8]
    },
    {
        bitkiAdi:'Ficus elastica - KAUÇUK',
        yetenekler:['radyasyon-emer','hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['cok-bakim'],
        isikIstegi:['aydinlik', 'yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['dikey'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[13]
    },
    {
        bitkiAdi:'Codiaeum variegatum - KROTON',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['cok-bakim'],
        isikIstegi:['yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['dikey'],
        sicaklik:['az'],
        nem: ['yuksek'],
        imageUrl: images[14]
    },
    {
        bitkiAdi:'Calathea Ornata- DUA ÇİÇEĞİ',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['cok-bakim'],
        isikIstegi:['yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['daginik'],
        sicaklik:['az'],
        nem: ['yuksek'],
        imageUrl: images[7]

    },
    {
        bitkiAdi:'Pilea Peperomioides-ÇİN PARA- PİLEA',
        yetenekler:[],
        tarz: ['tropik','minimal'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['yari-aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['ev'],
        imageUrl: images[18]
    },
    {
        bitkiAdi:'Zamioculcas Zamiifolia - ZAMİA',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['yari-aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['kucuk'],
        form:['dikey'],
        sicaklik:['dusuk'],
        nem: ['ev'],
        imageUrl: images[22]
    },
    {
        bitkiAdi:'Stralitzia Nicolai -STARLİÇE',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat', 'ciddi'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['buyuk'],
        form:['dikey'],
        sicaklik:['yuksek'],
        nem: ['yuksek'],
        imageUrl: images[13]
    },
    {
        bitkiAdi:'Dypsis Lutescens -AREKA PALMİYESİ',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['ev'],
        imageUrl: images[3]
    },
    {
        bitkiAdi:'Asparagus plumosus - KUŞKONMAZ',
        yetenekler:[],
        tarz: ['minimal','tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['yuksek'],
        isikIstegi:['aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['az'],
        nem: ['yuksek'],
        imageUrl: images[15]
    },
    {
        bitkiAdi:'Ficus benjamina - BENJAMİN',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['yuksek'],
        isikIstegi:['golge','yari-aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[6]
    },
    {
        bitkiAdi:'Dieffenbachia Seguine - DİFENBAHYA',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['golge','yari-aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['buyuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[9]
    },
    {
        bitkiAdi:'Opuntia M. Albata - KAKTÜS TAVŞAN K.',
        yetenekler:['radyasyon-emer'],
        tarz: ['col','minimal'],
        hissiyat:['ciddi','rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik','yari-aydinlik','golge'],
        buyume:['yavas'],
        yaprakOzelligi:['diken'],
        form:['dikey'],
        sicaklik:['yuksek'],
        nem: ['ev'],
        imageUrl: images[12]
    },
    {
        bitkiAdi:'Sansevieria Trifasciata - PAŞA KILICI',
        yetenekler:['hava-temizler'],
        tarz: ['col'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik','yari-aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['diken'],
        form:['dikey'],
        sicaklik:['dusuk'],
        nem: ['ev'],
        imageUrl: images[17]
    },
    {
        bitkiAdi:'Yucca elephantipes - YUKKA',
        yetenekler:[],
        tarz: ['col'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['yavas'],
        yaprakOzelligi:['diken','buyuk'],
        form:['dikey'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[21]
    },
    {
        bitkiAdi:'Aloe Barbadensis Miller - ALOE VERA',
        yetenekler:['hava-temizler'],
        tarz: ['tropik','minimal'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['diken'],
        form:['daginik'],
        sicaklik:['dusuk'],
        nem: ['ev'],
        imageUrl: images[0]
    },
    {
        bitkiAdi:'Euphorbia trigona - SÜT AĞACI',
        yetenekler:['radyasyon-emer'],
        tarz: ['col'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['diken','kucuk'],
        form:['dikey'],
        sicaklik:['orta'],
        nem: ['ev'],
        imageUrl:images[11]
    },
    {
        bitkiAdi:'Dracena Marginata - MADAGASKAR DRA',
        yetenekler:['hava-temizler'],
        tarz: ['col'],
        hissiyat:['ciddi'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['diken'],
        form:['dikey'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[10]
    },
    {
        bitkiAdi:'Pachira Aquatica - ÇİN PARA AĞACI',
        yetenekler:[],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['aydinlik','yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[16]
    },
    {
        bitkiAdi:'Spathiphyllum wallisii - BARIŞ ÇİÇEĞİ',
        yetenekler:['radyasyon-emer', 'hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:['cicekli'],
        bakimIstegi:['cok'],
        isikIstegi:['golge','yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['daginik'],
        sicaklik:['orta'],
        nem: ['yuksek'],
        imageUrl: images[5]
    },
    {
        bitkiAdi:'Anthurium - ANTORYUM',
        yetenekler:['hava-temizler'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:['cicekli'],
        bakimIstegi:['cok'],
        isikIstegi:['aydinlik','golge','yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['buyuk'],
        form:['daginik'],
        sicaklik:['yuksek'],
        nem: ['yuksek'],
        imageUrl: images[1]
    },
    {
        bitkiAdi:'Pothos - SALON SARMAŞIĞI',
        yetenekler:['hava-temizler','radyasyon-emer'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['az'],
        isikIstegi:['golge','yari-aydinlik'],
        buyume:['hizli'],
        yaprakOzelligi:['kucuk'],
        form:['sarkici'],
        sicaklik:['dusuk'],
        nem: ['ev'],
        imageUrl: images[19]
    },
    {
        bitkiAdi:'Nephrolepsis exaltata - AŞK MERDİVENİ',
        yetenekler:['hava-temizler','radyasyon-emer'],
        tarz: ['tropik'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['cok'],
        isikIstegi:['yari-aydinlik','golge'],
        buyume:['hizli'],
        yaprakOzelligi:['kucuk'],
        form:['sarkici'],
        sicaklik:['dusuk'],
        nem: ['yuksek'],
        imageUrl: images[4]
    },
    {
        bitkiAdi:'Chamaedora elegans- DAĞ PALMİYESİ',
        yetenekler:[],
        tarz: ['tropik','minimal'],
        hissiyat:['rahat'],
        renkli:[],
        bakimIstegi:['cok'],
        isikIstegi:['yari-aydinlik'],
        buyume:['orta'],
        yaprakOzelligi:['kucuk'],
        form:['daginik'],
        sicaklik:['dusuk'],
        nem: ['yuksek'],
        imageUrl:images[2]
    },
]
